### PR TITLE
Added Firebase as a dependency + Added send data functionality + rece…

### LINKED ISSUE #1: 1. As a component, I want to be able to read from and write to the Firestore database so that users can persist information.
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.
AC:
*  [`firebase`](https://www.npmjs.com/package/firebase) has been added as a project dependency
* Making a change in the Firestore database will update the data in the app
* Making a change in the app will update the data in Firestore

Notes:
* Don't do too much here. In the past, pairs have built the whole add item form in the first week. The best approach is just to make a throw away view with a `<button/>` and a `<div/>`. Click the `<button/>` to send some data to the database. Have the data show up in the `<div/>`. Simple!
* If you need additional direction on how to use Firebase, you can read through the [Quickstart Guide](https://firebase.google.com/docs/firestore/quickstart) for understanding how to [add items to Firestore](https://firebase.google.com/docs/firestore/quickstart#add_data), as well as the Snapshot Guide for [creating a snapshot subscription](https://firebase.google.com/docs/firestore/query-data/listen#listen_to_multiple_documents_in_a_collection) to read and update data in real-time.

---

Quick Tips:
<details>
<summary>How to send data to Firestore</summary>

```javascript
      import { collection, addDoc } from 'firebase/firestore'
      try {
          const docRef = await addDoc(collection(db, COLLECTION_NAME), {
            property: 'value'
            // ...data
          })
          // Success!
          console.log(docRef.id)
      } catch (e) {
          // There was an error sending data to Firestore
          console.error(e)
      }
```

</details>

<details>
<summary>How to listen to data from Firestore</summary>

```javascript
      import { collection, onSnapshot } from 'firebase/firestore'
      const [docs, setDocs] = useState([])
      useEffect(() => {
          const unsubscribe = onSnapshot(collection(db, COLLECTION_NAME), (snapshot) => {
            // Firestore requires that you loop through the snapshot to access the docs,
            // instead of just setting the snapshot as the value of the state
            const snapshotDocs = []
            snapshot.forEach(doc => snapshotDocs.push(doc))
            setDocs(snapshotDocs)
          })
          return () => {
            // Used to remove the snapshot listener when the component is unmounted
            unsubscribe();
          }
      }, [])
```

</details>

### PR DESCRIPTION
**Pull request by simonkaine**
## Description

This PR is updating the dependencies to add in Firebase, as well as adding in two new components `AddItem` and `List`. The `List` component uses the `onSnapshot` method from Firestore to listen to the document so that each time the content changes, it will update the data in the app. The `AddItem` component built the basic initial functionality to hook up the project so that any changes made in the app will update the data in Firestore. We did this by using the `addDoc` method from Firestore.

We decided to add these functionalities into two new components as we determined that they would be different views for the user within the app. 

## Related Issue

Closes #1 

## Acceptance Criteria

- [X] [firebase](https://www.npmjs.com/package/firebase) has been added as a project dependency
- [X] Making a change in the Firestore database will update the data in the app
- [X] Making a change in the app will update the data in Firestore

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
| ✓ | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

Started from scratch

### After

The UI is very simple as we were focusing on the functionality and not styling.
Screen Shot 2022-04-08 at 11 27 19 AM

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with `git pull origin sk-rt-connect-to-firestore` and check that branch out with `git checkout sk-rt-connect-to-firestore`
- Use `npm install` to install the newly added dependencies locally and `npm start` to launch the app.
- Click on the "Click to submit new item" button and make sure it adds an item to the list (should be another "banana"). Open up the database to check that it is appearing in the list of items collection [here](https://console.firebase.google.com/u/0/project/tcl-43-smart-shopping-list/firestore/data/~2FShopping-List~2FwxGXR3Kk93w0tMObuqAl). 
- While in the Firestore Database, click on "Add document" under the Shopping-List column. For the document, ID click on the blue "Auto-ID". For field, enter in `item` and add a value of an item you'd like to add to the shopping list! Click save, then navigate back to your browser tab that has the app running, and you should see your list item appear!

### CODE REVIEW

**Comment by rachael-t** [comment]
Updated PR - ready for peer review!

**Review by nikkigraybeal — APPROVED** [review]

**Comment by lena-A-Al** [comment]
I run the UI locally and looks good.

**Review by lena-A-Al — APPROVED** [review]
I run the UI locally and looks good.

**Review by emilygracekz — APPROVED** [review]
Nice job! It works as it needs to and looks clean.

**Pull request merged**
